INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Boost HP', 'Increase hp by 40%.', 40, 1, 0);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Boost Stamina', 'Increase stamina by 20%.', 20, 1, 1);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Iron will', 'Increase defense by 25%.', 25, 1, 2);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Inner power', 'Increase attack by 25%.', 25, 1, 3);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Balance', 'Increase attack and defense by 10%.', 10, 1, 4);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Sacrifice', 'Decrease stamina by 30% and increase health by 40%.', 10, 1, 5);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Body to mind', 'Decrease hp by 30% and increase stamina by 40%.', 10, 1, 6);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Beast', 'Increase attack by 15% and critical rate by 20%.', 10, 1, 7);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Berserker', 'Decrease defense by 40%, increase attack by 30%, increase critical rate by 30% and critical damage by 40%, lasts 3 battles. 4h cooldown.', 10, 1, 8);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Through the heart', 'Decrease your attack and defense by 5%, increase your critical rate and damage by 15%.', 10, 1, 9);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Deep breath', 'Increase your health regeneration by 25%.', 10, 1, 10);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Replenish', 'Increase your stamina regeneration by 10%.', 10, 1, 11);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Anvil', 'Decrease attack by 75%, critical rate and damage by 60%, increase health and defense by 90%.', 10, 1, 12);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Undead hate', 'Increase damage against zombies by 20%.', 10, 1, 13);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Dragon frenzy', 'Decrease defense by 20%, increase attack by 40%, increase critical rate by 15%, only against dragons.', 10, 1, 14);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Lucky', 'Increase chance of monster find by 30% on top of normal rate.', 10, 1, 15);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Superstitious', 'There is a 0.2% of dispatch a lethal hit, 5% chance of replenish all stamina and 10% chance of recovery full health after win a battle.', 10, 1, 16);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Illusionist', 'There is a 15% chance of deal a second attack after a critical hit.', 10, 1, 17);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Ghost', 'There is a 10% chance of dodge income attacks.', 10, 1, 18);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Last resort', 'Increase 50% defense when health below 15%.', 10, 1, 19);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Finisher', 'Increase attack and critical rate by 30% when opponent is below 20% health.', 10, 1, 20);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Reborn', 'Recovery 35% health when dodge income attacks.', 10, 1, 21);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Bloodthirst', 'Recovery 5% health on critical hits.', 10, 1, 22);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Never-fading', 'Revives with 20% health when die by a critical hit.', 10, 1, 23);
INSERT INTO skill(st_name, st_description, nr_power, nr_required_level, st_type) VALUES('Extractor', 'Increase dragon\'s blood find chance by 10% when kill another hero.', 10, 1, 24);